### ISSUE TITLE
go get issue on n.Attr

### ISSUE THREAD

**Issue by fils** [asciimoo/colly#13]
On Mac with go version 1.9

```
Fils:collyIndexer dfils$ go get github.com/asciimoo/colly
# github.com/asciimoo/colly
../../../../github.com/asciimoo/colly/colly.go:302:16: cannot use n.Attr (type []"code.google.com/p/go.net/html".Attribute) as type []"golang.org/x/net/html".Attribute in field value
Fils:collyIndexer dfils$ go version
go version go1.9 darwin/amd64
```

**Comment by asciimoo** [comment]
Probably your goquery package is outdated, try to run `go get -u github.com/PuerkitoBio/goquery` before getting Colly.

**Comment by NafisFaysal** [comment]
@asciimoo so we can vendor the third party package for this kind of issue :smiley: I already did it on #12 .

**Comment by asciimoo** [comment]
@NafisFaysal you're right, #12 pulled. Thanks!
