### ISSUE TITLE
Do you have any plan to support proxy and encode/decode?

### ISSUE THREAD

**Issue by tx991020** [asciimoo/colly#18]
Do you have any plan to support proxy and encode/decode?

**Comment by asciimoo** [comment]
@tx991020 You can use proxy by setting custom HTTP transport (https://golang.org/pkg/net/http/#Transport) with Collector's `WithTransport(*http.Transport)` function.

What does encode/decode support mean?

**Comment by tx991020** [comment]
c.Visit("http://www.qq.com/")， when the charset is not utf-8 , the response will like this ���������PM2.5�������. 
I hope like  python  requests . When  the  charset is not utf-8.  Colly  support  encode/decode 
import requests
r = requests.get('http://www.qq.com/')
r.encoding='gbk'

**Comment by asciimoo** [comment]
@tx991020 hopefully it is fixed in 47bdf58 could you verify it?
