### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by kataras** [asciimoo/colly#19]
Hello @asciimoo , good job with the lib!

I just wanted to say that I did [open a PR](https://github.com/avelino/awesome-go/pull/1615) 5 days ago to add your project inside the "awesome-go" directory.

The README doesn't contain any quality references, like report card, so I took the liberty to complete them inside the PR text, please add them as badges to the README.md of this repository as well, the links are:

- godoc.org: https://godoc.org/github.com/asciimoo/colly
- goreportcard.com: https://goreportcard.com/report/github.com/asciimoo/colly

However in order (the PR) to be acceptable we have to complete some other links as well, like the coverage service link, it looks like this: https://cover.run/go/github.com/asciimoo/colly.svg 
but I couldn't find any tests (`_test.go` files) of "colly" so the PR was marked as "pending".

Please keep watching this and do your bests to complete some test files, those details matters there. 

**Thank you!**

**Comment by asciimoo** [comment]
Hello @kataras, first of all thanks for submitting Colly to "awesome-go" (and for your fabulous framework, iris =] ).
I'll add the badges to the README and tests to the repo soon.

**Comment by kataras** [comment]
Thank you for your nice words, I'll be glad to see your framework there, it's very easy to use and it's based on a good library that I used before as well!

**Comment by asciimoo** [comment]
@kataras i've added the badges and some tests.

**Comment by kataras** [comment]
Good job! I added these to the PR description, let's wait for answer :)
