### ISSUE TITLE
how to auth(login) before request?

### ISSUE THREAD

**Issue by kk44** [asciimoo/colly#20]
any example? thanks！:-)

**Comment by asciimoo** [comment]
@kk44 it depends on how do you want to authenticate.

HTTP basic auth can be handled in OnRequest callbacks, by setting the auth header to `Request.Headers`.
If you'd like to submit a login form, probably `Collector.Post` will be your friend, where you can post your username/password.
In case of Oauth, the easiest way is doing the auth with a browser and copying the session cookies to your scraper (use `Collector.SetCookie()`/`Collector.SetCookies()` functions).

**Comment by kk44** [comment]
@asciimoo Thank you! I'll try later
