### ISSUE TITLE
How to use colly for a second time in a code?

### ISSUE THREAD

**Issue by Frodgy** [asciimoo/colly#21]
Do I have to initialize a new collector? It doesn't work after this.

**Comment by asciimoo** [comment]
@Frodgy It should work, do you have an example code?

Creating a collector isn't that expensive, so if there is no reason to use the previously created one (e.g. preserving cookies or HTTP keep-alive), it's recommended to initialize a new one for every scraping task.
`Collector` doesn't visit an url more than once if `Collector.AllowURLRevisit` attribute isn't `true`, perhaps this causes your problem

**Comment by Frodgy** [comment]
My fault - I didn't pay an exact attention to the hosts redirection. Thanks anyway, everything works.
