### ISSUE TITLE
robots.txt support

### ISSUE THREAD

**Issue by voidpirate** [asciimoo/colly#27]
Does it make sense to support abiding by the website `robots.txt`?

**Comment by asciimoo** [comment]
@voidpirate yes, this is definitely a good optional feature, thank you. Could you work on this?

**Comment by voidpirate** [comment]
I can.

**Comment by vosmith** [comment]
Is this being worked on.  Looks like it should just be a few lines of code if you integrate with https://github.com/temoto/robotstxt

**Comment by voidpirate** [comment]
I planned on working on this, just haven't allocated the time as I have been busy with my job. 

If anyone else wants to take this over feel free to.

**Comment by asciimoo** [comment]
closed by 5bc9a6c
