### ISSUE TITLE
I think  c.Limit  also can  be used to filter unmatched urls  . Should support regex  before request   in anywhere. 

### ISSUE THREAD

**Issue by tx991020** [asciimoo/colly#29]
The purpose is to filter out the mismatched urls

for example
package main

import (
	"github.com/asciimoo/colly"
	"fmt"
	"time"
)

func main() {
	urls := []string{"https://httpbin.org/hello", "https://httpbin.org/123", "https://httpbin.org/12xyz"}

	// Instantiate default collector
	c := colly.NewCollector()

	// when visiting links which domains' matches "*httpbin.*" glob
	c.Limit(&colly.LimitRule{
		DomainGlob: "*https://httpbin.org/[a-z]+",
	})
	c.OnResponse(func(r *colly.Response) {
		fmt.Println("Finished", r.Request.URL, time.Now())
	})

	for _, i := range urls {
		c.Visit(i)
	}
	

	
     c.Wait()
}
Starting https://httpbin.org/hello",
Starting "https://httpbin.org/123",
Starting "https://httpbin.org/12xyz
Finished  https://httpbin.org/hello

**Comment by asciimoo** [comment]
@tx991020 this would be a useful feature, however `LimitRule` works a bit different than in your example. Currently it specifies **restrictions** to the matching domains and you want to **allow** URLs with these rules. I'm not sure if extending `LimitRule` is the correct way to achieve this functionality.

**Comment by asciimoo** [comment]
@tx991020 I could imagine this as an independent feature - e.g. `c.AddURLFilter(urlGlob string)` or something similar. Thoughts?

**Comment by tx991020** [comment]
yes.

**Comment by meehow** [comment]
In my understanding `Limit` it's something what limits resources used by a program. You need to extract URLs in code of your program anyway.
Isn't your code a good place to add some regexp?

**Comment by meehow** [comment]
I would rather add `c.URLFilters []*regexp.Regexp` to make sure before crawling that regexps are correct.
