### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by vosmith** [asciimoo/colly#37]
What are your thoughts on adding proxy support to the `Collector`?  I see that one could just create a custom `Transport` and set the collector to use it, but it would be nice to have a `SetProxy(url)` method or something similar.

**Comment by vosmith** [comment]
I think this issue is closed by c1a71b6cb01c12f2d1ff61425d06b5ae67b5f512

**Comment by asciimoo** [comment]
Yup, thanks @gummiboll
