### ISSUE TITLE
Feature Request: Ability to submit forms

### ISSUE THREAD

**Issue by sebastianmacias** [asciimoo/colly#41]
Are you planning to support the ability to submit forms, keep the cookies while visiting a different page, and some basic user interaction actions?

Thanks

**Comment by sebastianmacias** [comment]
[grequests](https://github.com/levigross/grequests) could be used to submit forms, process file uploads, etc.

**Comment by asciimoo** [comment]
Colly supports the requested features. It stores cookies automatically and has functions to send form data:
 * https://godoc.org/github.com/asciimoo/colly#Collector.Post
 * https://godoc.org/github.com/asciimoo/colly#Collector.PostMultipart

**Comment by sebastianmacias** [comment]
Perfect!  Thanks for posting the links.

**Comment by Splik** [comment]
@asciimoo, could you explain how can I send FormData:

The following requests with the following params returns 500 rows proxy list (http://spys.one/en/http-proxy-list).
![s](https://api.monosnap.com/rpc/file/download?id=MqdyNx4V4UyTFaeL12Vd9gk7Jcqzee)

I've experimented with the following ways:

<details>
  <summary>Click to expand</summary>

  ```
  // 1
  collector.PostRaw(
  	"http://spys.one/en/http-proxy-list",
  	[]byte(
  		fmt.Sprintf("xpp:5\r\nxf1:0\r\nxf2:2\r\nxf4:2\r\nxf5:1"),
  	),
  )

  // 2
  formData := map[string]string{
  	"xpp": "5",
  	"xf1": "0",
  	"xf2": "2",
  	"xf4": "2",
  	"xf5": "1",
  }
  form := url.Values{}
  for k, v := range formData {
  	form.Add(k, v)
  }
  collector.PostRaw(
  	"http://spys.one/en/http-proxy-list",
  	[]byte(form.Encode()),
  )

  // 3
  collector.Post(
  	"http://spys.one/en/http-proxy-list",
  	map[string]string{
  		"xpp": "5",
  		"xf1": "0",
  		"xf2": "2",
  		"xf4": "2",
  		"xf5": "1",
  	},
  )

  // 4
  collector.PostMultipart(
  	"http://spys.one/en/http-proxy-list",
  	map[string][]byte{
  		"xpp": []byte("5"),
  		"xf1": []byte("0"),
  		"xf2": []byte("2"),
  		"xf4": []byte("5"),
  		"xf5": []byte("1"),
  	},
  )
  ```
</details>

But they return 30 rows proxy list. Looks like those params are ignored.

**Comment by asciimoo** [comment]
It works for me if I append the trailing slash to the end of the URL like in your screenshot:
```go
package main

import (
    "fmt"
    "github.com/gocolly/colly"
)

func main() {
    c := colly.NewCollector()
    c.OnHTML("tr.spy1x,tr.spy1xx", func(e *colly.HTMLElement) {
        fmt.Println(e)
    })
    fmt.Println(c.Post(
        "http://spys.one/en/http-proxy-list/",
        map[string]string{
            "xpp": "5",
            "xf1": "0",
            "xf2": "0",
            "xf4": "0",
            "xf5": "0",
        },
    ))
}

```

**Comment by Splik** [comment]
@asciimoo, it works for me too. 

![s](https://media.giphy.com/media/3og0INyCmHlNylks9O/source.gif)

I should have tried to post with the trailing slash. 

Thanks so much. 👍
