### ISSUE TITLE
Passing context between collectors

### ISSUE THREAD

**Issue by mfpierre** [asciimoo/colly#48]
I was wondering how it's possible to pass context between collectors.

My use case is that I have a collector that is collecting links and the triggers another collector to visit this link. On the second collector, I'd like to pass some sort of context (like a parent category name that is not present on the child page HTML) but I didn't find a way to achieve this because `Context` seems only for request/responses within the same collector.

**Comment by asciimoo** [comment]
@mfpierre use `Collector.Request`[1] method, it accepts custom context argument so you can pass the context to the second collector.

[1] https://godoc.org/github.com/asciimoo/colly#Collector.Request

**Comment by mfpierre** [comment]
@asciimoo thanks, perfect! I missed this one 🔍
