### ISSUE TITLE
Multipart support

### ISSUE THREAD

**Issue by kawakami-o3** [asciimoo/colly#8]
Do you have any plan to support a multipart POST request?
I will code this feature later.

**Comment by asciimoo** [comment]
@kawakami-o3 this is definitely a missing and useful feature. I'd appreciate if you could implement it.

**Comment by vosmith** [comment]
So I started working on this and gave it a good try.  The main issue that there is no way to set custom headers.

Right now all `POST` requests are forced into the content-type `application/x-www-form-urlencoded`.

I tried creating new functions for like 

    func (c *Collector) PostMultipart ...

But once it hits `scrape`, the content gets set.  I also tried adding an `onRequest` callback method to set the header, but then this callback affects all successive requests once it becomes a part of the callback stack.

Frankly I found it difficult to accomplish this without significant changes to how the headers are handled.

**Comment by asciimoo** [comment]
> So I started working on this and gave it a good try. 

Awesome! =)

> Right now all POST requests are forced into the content-type application/x-www-form-urlencoded

What about adding a new "Content-Type" string parameter to `scrape()` function and in case it is not empty we set the content type to that?

**Comment by vosmith** [comment]
Sounds like it should work! I'll go ahead and give it a try👍🏾

**Comment by kawakami-o3** [comment]
I am late...
I planed to add a request data handler instead of `requestData map[string]string`.
If the handler contains a file, it can decide correct Content-Type.

Should I stop my work?

**Comment by asciimoo** [comment]
@kawakami-o3 seems like @vosmith nearly finished the implementation. Let's wait for his solution to avoid duplicated work. What do you think?

**Comment by kawakami-o3** [comment]
I follow you.

**Comment by asciimoo** [comment]
added in 30e15f6 thank you for your work.
